version: "2"
run:
  tests: true
linters:
  enable:
    - copyloopvar
    - goconst
    - gocritic
    - gosec
    - misspell
    - nakedret
    - nestif
    - revive
    - staticcheck
    - thelper
    - unconvert
    - unparam
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - blank
        - dot
        - prefix(cosmossdk.io)
        - prefix(github.com/cosmos/cosmos-sdk)
        - prefix(github.com/cometbft/cometbft)
        - prefix(github.com/cosmos/ibc-go)
      no-inline-comments: true
      no-prefix-comments: true
      custom-order: true
      no-lex-order: true    
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
